using HtmlAgilityPack;
using SportsResults.Forser.Models;

namespace SportsResults.Forser.Services
{
    internal class Scraper : IScraper
    {
        public Scraper() { }
        public HtmlDocument LoadWebsite(string url)
        {
            HtmlWeb htmlWeb = new HtmlWeb();

            return htmlWeb.Load(url);
        }
        public string GetDateOfResults(HtmlDocument htmlDoc)
        {
            return htmlDoc.DocumentNode.SelectSingleNode("//div[@class='index']/h1").InnerText;
        }
        public List<HtmlNode> GetAllNodes(HtmlDocument htmlDoc)
        {
            return htmlDoc.DocumentNode.SelectNodes("//div[@class='game_summary expanded nohover ']").ToList();
        }
        public List<GameModel> GenerateGameModel(List<HtmlNode> htmlNodes)
        {
            List<GameModel> games = new List<GameModel>();

            foreach (var gameNode in htmlNodes)
            {
                GameModel game = new GameModel
                {
                    HomeTeam = gameNode.SelectSingleNode(".//tr[@class='winner']/td[1]").InnerText,
                    AwayTeam = gameNode.SelectSingleNode(".//tr[@class='loser']/td[1]").InnerText,
                    HomeScore = gameNode.SelectSingleNode(".//tr[@class='winner']/td[2]").InnerText,
                    AwayScore = gameNode.SelectSingleNode(".//tr[@class='loser']/td[2]").InnerText
                };
                games.Add(game);
            }

            return games;
        }
        public string GenerateEmail(List<GameModel> gameModels, string title)
        {
            string mailHeader = $"<b>{title}</b><br/><br/>";
            string mailBody = "";

            foreach (var game in gameModels)
            {
                mailBody += $"Home Team: {game.HomeTeam} - Away Team: {game.AwayTeam}<br/>" + 
                    $"Home Score: {game.HomeScore} - Away Score: {game.AwayScore}<br/>" + 
                    "------------------------------------------------------------<br/>";
            }

            string mailFooter = $"This email was auto-generated by a background worker, notifying you of the NBA results once a day";

            return mailHeader + mailBody + mailFooter;
        }
    }
}